name:                satellite
version:             0.1.0.0
github:              "zietzm/satellite"
license:             BSD-3-Clause
author:              "Michael Zietz"
maintainer:          "michael.zietz@gmail.com"
copyright:           "2025 Michael Zietz"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/zietzm/satellite#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.6 && < 0.6
- dsp >= 0.2.5 && < 0.3
- vector >= 0.13.1 && < 0.14
- vector-fftw >= 0.1.4 && < 0.2
- wave >= 0.2.1 && < 0.3
- vector-algorithms >= 0.9.0 && < 0.10
- bytestring
- JuicyPixels
- cereal

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  satellite-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satellite

tests:
  satellite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satellite
    - tasty
    - tasty-hunit
